-- Supabase Migration: MCU Tables
-- Generated automatically

CREATE TABLE public.mcu_records (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    national_id TEXT,
    nik_karyawan TEXT,
    nama TEXT,
    usia NUMERIC,
    jenis_kelamin TEXT,
    jabatan TEXT,
    site TEXT,
    status_mcu TEXT,
    tgl_mcu DATE,
    tempat_mcu TEXT,
    gol_darah TEXT,
    gigi_mulut TEXT,
    fisik_head_to_toe TEXT,
    hemoroid TEXT,
    visus_jauh TEXT,
    visus_dekat TEXT,
    def_warna TEXT,
    lapang_pandang TEXT,
    fisik_mata TEXT,
    merokok TEXT,
    td_s NUMERIC,
    td_d NUMERIC,
    nadi NUMERIC,
    bb NUMERIC,
    tb NUMERIC,
    bmi NUMERIC,
    lp NUMERIC,
    hb NUMERIC,
    leukosit NUMERIC,
    eritrosit NUMERIC,
    hematokrit NUMERIC,
    trombosit NUMERIC,
    mcv NUMERIC,
    mch NUMERIC,
    mchc NUMERIC,
    led NUMERIC,
    chol NUMERIC,
    tg NUMERIC,
    hdl NUMERIC,
    ldl NUMERIC,
    gdp NUMERIC,
    gd2pp NUMERIC,
    hba1c NUMERIC,
    diabetes TEXT,
    au NUMERIC,
    ureum NUMERIC,
    kreatinin NUMERIC,
    egfr NUMERIC,
    sgot NUMERIC,
    sgpt NUMERIC,
    ggt NUMERIC,
    alp NUMERIC,
    billirubin NUMERIC,
    ul TEXT,
    hbsag TEXT,
    anti_hbs TEXT,
    vdrl TEXT,
    tpha TEXT,
    hiv TEXT,
    drug_amp TEXT,
    drug_meth TEXT,
    drug_morph TEXT,
    drug_canna TEXT,
    drug_coc TEXT,
    drug_benz TEXT,
    drug_caris TEXT,
    alkohol TEXT,
    psa NUMERIC,
    chest_xr TEXT,
    lumbo_xr TEXT,
    ecg_hasil TEXT,
    tm_hasil TEXT,
    usg TEXT,
    fvc_pred NUMERIC,
    fvc_act NUMERIC,
    fvc_pct NUMERIC,
    fev1_pred NUMERIC,
    fev1_act NUMERIC,
    fev1_pct NUMERIC,
    fev1_fvc_pred NUMERIC,
    fev1_fvc_act NUMERIC,
    fev1_fvc_pct NUMERIC,
    spi_interp TEXT,
    acr_500 NUMERIC,
    acr_1k NUMERIC,
    acr_2k NUMERIC,
    acr_3k NUMERIC,
    acr_4k NUMERIC,
    acr_6k NUMERIC,
    acr_8k NUMERIC,
    acl_500 NUMERIC,
    acl_1k NUMERIC,
    acl_2k NUMERIC,
    acl_3k NUMERIC,
    acl_4k NUMERIC,
    acl_6k NUMERIC,
    acl_8k NUMERIC,
    aud_interp TEXT,
    balance TEXT,
    romberg TEXT,
    phalen TEXT,
    thinel TEXT,
    patrick TEXT,
    kontra_patrick TEXT,
    laseque TEXT,
    kernig TEXT,
    tes_kebugaran TEXT,
    pemeriksaan_lain TEXT,
    dugaan_pak TEXT,
    kes_vendor TEXT,
    rek_qshe TEXT,
    diagnosa_medis TEXT,
    perlu_fu TEXT,
    rek_fu TEXT,
    item_fu TEXT,
    link_mcu TEXT,
    tgl_expired DATE,
    fram_score NUMERIC,
    fram_prob TEXT,
    fram_kat TEXT,
    zonasi TEXT,
    trigger_zona TEXT,
    pengendalian TEXT,
    tgl_fu1 DATE,
    lokasi_fu1 TEXT,
    hasil_fu1 TEXT,
    kesimpulan_fu1 TEXT,
    link_fu1 TEXT,
    rek_fu2 TEXT,
    tgl_fu2 DATE,
    lokasi_fu2 TEXT,
    hasil_fu2 TEXT,
    kesimpulan_fu2 TEXT,
    link_fu2 TEXT,
    rek_fu3 TEXT,
    tgl_fu3 DATE,
    lokasi_fu3 TEXT,
    hasil_fu3 TEXT,
    kesimpulan_fu3 TEXT,
    link_fu3 TEXT,
    rek_fu4 TEXT,
    catatan TEXT,
    national_id_hash TEXT,
    nik_karyawan_hash TEXT
);
CREATE INDEX mcu_records_national_id_hash_idx
  ON public.mcu_records (national_id_hash);

CREATE INDEX mcu_records_nik_karyawan_hash_idx
  ON public.mcu_records (nik_karyawan_hash);

CREATE OR REPLACE FUNCTION update_modified_column()   
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;   
END;
$$ language 'plpgsql';

DROP TRIGGER IF EXISTS update_mcu_records_modtime ON public.mcu_records;
CREATE TRIGGER update_mcu_records_modtime
BEFORE UPDATE ON public.mcu_records 
FOR EACH ROW EXECUTE PROCEDURE update_modified_column();

DROP VIEW IF EXISTS public.mcu_monitor_all_site;
CREATE OR REPLACE VIEW public.monitor_mcu AS
WITH ranked_mcu AS (
  SELECT *,
    ROW_NUMBER() OVER(
      PARTITION BY COALESCE(nik_karyawan_hash, national_id_hash)
      ORDER BY tgl_mcu DESC NULLS LAST, created_at DESC
    ) AS rn
  FROM public.mcu_records
)
SELECT
  national_id,
  nik_karyawan,
  nama,
  usia,
  jenis_kelamin,
  jabatan,
  site,
  status_mcu,
  tgl_mcu,
  tempat_mcu,
  gol_darah,
  gigi_mulut,
  fisik_head_to_toe,
  hemoroid,
  visus_jauh,
  visus_dekat,
  def_warna,
  lapang_pandang,
  fisik_mata,
  merokok,
  td_s,
  td_d,
  nadi,
  bb,
  tb,
  bmi,
  lp,
  hb,
  leukosit,
  eritrosit,
  hematokrit,
  trombosit,
  mcv,
  mch,
  mchc,
  led,
  chol,
  tg,
  hdl,
  ldl,
  gdp,
  gd2pp,
  hba1c,
  diabetes,
  au,
  ureum,
  kreatinin,
  egfr,
  sgot,
  sgpt,
  ggt,
  alp,
  billirubin,
  ul,
  hbsag,
  anti_hbs,
  vdrl,
  tpha,
  hiv,
  drug_amp,
  drug_meth,
  drug_morph,
  drug_canna,
  drug_coc,
  drug_benz,
  drug_caris,
  alkohol,
  psa,
  chest_xr,
  lumbo_xr,
  ecg_hasil,
  tm_hasil,
  usg,
  fvc_pred,
  fvc_act,
  fvc_pct,
  fev1_pred,
  fev1_act,
  fev1_pct,
  fev1_fvc_pred,
  fev1_fvc_act,
  fev1_fvc_pct,
  spi_interp,
  acr_500,
  acr_1k,
  acr_2k,
  acr_3k,
  acr_4k,
  acr_6k,
  acr_8k,
  acl_500,
  acl_1k,
  acl_2k,
  acl_3k,
  acl_4k,
  acl_6k,
  acl_8k,
  aud_interp,
  balance,
  romberg,
  phalen,
  thinel,
  patrick,
  kontra_patrick,
  laseque,
  kernig,
  tes_kebugaran,
  pemeriksaan_lain,
  dugaan_pak,
  kes_vendor,
  rek_qshe,
  diagnosa_medis,
  perlu_fu,
  rek_fu,
  item_fu,
  link_mcu,
  tgl_expired,
  fram_score,
  fram_prob,
  fram_kat,
  zonasi,
  trigger_zona,
  pengendalian,
  tgl_fu1,
  lokasi_fu1,
  hasil_fu1,
  kesimpulan_fu1,
  link_fu1,
  rek_fu2,
  tgl_fu2,
  lokasi_fu2,
  hasil_fu2,
  kesimpulan_fu2,
  link_fu2,
  rek_fu3,
  tgl_fu3,
  lokasi_fu3,
  hasil_fu3,
  kesimpulan_fu3,
  link_fu3,
  rek_fu4,
  catatan
FROM ranked_mcu
WHERE rn = 1;
